sponsors_crud:
    path: /sponsors
    controller: App\Controller\SponsorController::index
    methods: [GET]

sponsors_crud_id:
    path: /sponsors/{id}
    controller: App\Controller\SponsorController::update
    methods: [PATCH]
